plugins:
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/**/*'
    - 'build/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
