author:
  name: "Juanra Carretero"
  short_name: "Juanra"
  image_url: "https://avatars.githubusercontent.com/u/44867213"
  github_url: "https://github.com/JuanraCM"

bio:
  long_version: "I build software, break things (on purpose), and write about what I learn along the way. I'm endlessly curious about technology and love sharing my knowledge with others."
  short_version: "I build software, break things (on purpose), and write about what I learn along the way."
