author:
  name: "Juanra Carretero"
  short_name: "Juanra"
  image_url: "https://avatars.githubusercontent.com/u/44867213"
  github_url: "https://github.com/JuanraCM"

bio:
  long_version: "Experienced Software Engineer with a strong background in backend development, cloud computing, and DevOps practices. Passionate about building scalable and efficient systems."
  short_version: "Software Engineer specialized in backend development and cloud computing."
